ALTER TABLE app_user ADD COLUMN mfa_secret VARCHAR(255);
ALTER TABLE app_user ADD COLUMN mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE app_user ADD COLUMN mfa_locked BOOLEAN NOT NULL DEFAULT FALSE;
